### ISSUE TITLE
Add link to successor projects

### ISSUE THREAD

**Issue by ysangkok** [wjzz/Agda-mode-improvements#1]
I assume that this code is stale, since it hasn't been touched for 4 years. But I havn't found any modern code that aims to do the same. It would be useful to add a link in the README, so that people know what this was replaced by. Thanks.

**Comment by ysangkok** [comment]
Closing this since it clutters my issue list.

**Comment by wjzz** [comment]
Sorry for ignoring your comment for so many years. Unfortunately, I'm also unaware of any modern code, I've stopped fiddling with Agda and moved to other stuff (at least for now). Thanks anyway!
